import './globals.css'
import { Inter, Ubuntu } from 'next/font/google'

const inter = Ubuntu(
  {
    subsets: ['latin'],
    weight: ['300', '400', '500', '700'],
  }

)


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ inter.className } >{ children }</body>
    </html>
  )
}
